baseurl = "https://radio.clubs.etsit.upm.es"
title = "RadioClub EIT"
theme = "whiteclub"
languageCode = "es"
paginatePath = "blog"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 RadioClub EIT"

# Build future content [IMPORTANT]
buildfuture = true

# google analytics tracking id
googleAnalytics = "UA-155169045-1"

# Disqus shortname
disqusShortname = "radioclub-eit"

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  dateFormat = "2 January, 2006"
  description = "EA4RCT"
  avatar = "/logo.png"
  favicon = "/favicon.png"
  logo = "/favicon_big.png"
  twitter = "ea4rct"

  # Activities info
  [params.activities]

    # Using Google calendar on "insert calendar"
    calendarPublicURL = 'https://calendar.google.com/calendar/embed?src=ea4rct.org_h65bumho4rtdp5dlbkij1hulfc%40group.calendar.google.com&ctz=Europe%2FMadrid'

    # iframe from Google Calendar: Better without title, without print icon, using month, wight: 500, height: 400
    calendarIframe = '''
    <iframe src="https://calendar.google.com/calendar/b/2/embed?showTitle=0&amp;showDate=0&amp;showCalendars=0&amp;height=400&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=ea4rct.org_h65bumho4rtdp5dlbkij1hulfc%40group.calendar.google.com&amp;color=%23691426&amp;ctz=Europe%2FMadrid" style="border-width:0" width="500" height="400" frameborder="0" scrolling="no"></iframe>
    '''

# This is displayer in About page.
[params.about]
  twitter = "ea4rct"
  #github = "Github username"
  gitea = "http://git.radio.clubs.etsit.upm.es"
  email = "info@ea4rct.org"

  localizacion =  "Avenida Complutense Nº30 Local 101.3-L"
  codigopostal =  "28040, Madrid"
  metro = "Metro: Ciudad Universitaria, Vicente Aleixandre"
  cif = "G28939353"
  # telefono =
  #horario = "De lunes a viernes de 9 a 21"

# Slideshow of pictures on homepage.
[params.slideshow]
  [params.slideshow.pic1]
    file = "/slideshow/junta2021.jpg"
    title = "Junta 2020-21"
    desc = "Octubre 2020"
  [params.slideshow.pic2]
    file = "/slideshow/recepcionSept19.jpeg"
    title = "Recepción telemetría satélite Meteor desde el RadioClub"
    desc = "Septiembre 2019"
  [params.slideshow.pic3]
    file = "/slideshow/wearables.gif"
    title = "Taller de Wearables"
    desc = "Abril 2019"
  [params.slideshow.pic4]
    file = "/slideshow/taller-iss.jpeg"
    title = "Actividad de reparación de la ISS con SDR"
    desc = "Enero 2020"
  [params.slideshow.pic5]
    file = "/slideshow/taller-arduino.jpg"
    title = "Taller de arduino"
    desc = "Oct 2018"
  [params.slideshow.pic6]
    file = "/slideshow/radio.jpg"
    #title = "Fourth great pic"
    #desc = "This pic was on West Africa"
  [params.slideshow.pic7]
    file = "/slideshow/pedales.jpg"
    title = "Taller de pedales de guitarra"
    desc = "Feb 2019"

[taxonomies]
  category = "categorias"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Próximas actividades"
  identifier = "activities"
  url = "/activities/"
  weight = 1
[[menu.main]]
  name = "Proyectos"
  identifier = "proyectos"
  url = "/proyectos/"
  weight = 2
[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 3
[[menu.main]]
  name = "Categorias"
  identifier = "categorias"
  url = "/categorias/"
  weight = 4
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 5
[[menu.main]]
  name = "Archivo"
  identifier = "archives"
  url = "/archives/"
  weight = 6
[[menu.main]]
  name = "Quiénes somos"
  identifier = "team"
  url = "/team/"
  weight = 7
[[menu.main]]
  name = "Contacto"
  identifier = "about"
  url = "/about/"
  weight = 8

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
